# Generated by Django 4.1 on 2023-04-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stressdetection',
            name='question10',
        ),
        migrations.RemoveField(
            model_name='stressdetection',
            name='question11',
        ),
        migrations.RemoveField(
            model_name='stressdetection',
            name='question12',
        ),
    ]
